/**
 * Accumulates rows for thesis-docs/functional-validation-summary.md.
 */

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

/** Repository root (Playwright sets cwd to project root). */
export const REPO_ROOT = process.cwd();
export const FUNCTIONAL_REPORT_PATH = join(REPO_ROOT, "thesis-docs", "functional-validation-summary.md");
export const FUNCTIONAL_SCREENSHOT_DIR = join(
  REPO_ROOT,
  "thesis-docs",
  "functional-validation-screenshots",
);

export interface FunctionalReportRow {
  testName: string;
  area: string;
  expected: string;
  result: "PASS" | "FAIL";
  screenshotPath: string;
  notes: string;
}

const rows: FunctionalReportRow[] = [];

export function ensureScreenshotDir(): void {
  mkdirSync(FUNCTIONAL_SCREENSHOT_DIR, { recursive: true });
}

export function recordFunctionalResult(row: FunctionalReportRow): void {
  rows.push(row);
}

export function writeFunctionalReport(): void {
  const lines: string[] = [
    "# Functional Validation Summary",
    "",
    "This file is generated by the Playwright functional validation pass.",
    "",
    `Generated: ${new Date().toISOString()}`,
    "",
    "| Test name | Area | Expected behavior | Result | Screenshot path | Notes |",
    "| --- | --- | --- | --- | --- | --- |",
  ];

  for (const r of rows) {
    const safe = (s: string) => s.replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(
      `| ${safe(r.testName)} | ${safe(r.area)} | ${safe(r.expected)} | ${r.result} | ${safe(r.screenshotPath)} | ${safe(r.notes)} |`,
    );
  }

  lines.push("");
  writeFileSync(FUNCTIONAL_REPORT_PATH, lines.join("\n"), "utf8");
}

export function relativeScreenshotPath(filename: string): string {
  return join("thesis-docs", "functional-validation-screenshots", filename).replace(/\\/g, "/");
}
